# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\server_gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1943, 1100)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../static/icon/baseline_message_black_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMaximumSize(QtCore.QSize(531, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setIconSize(QtCore.QSize(44, 36))
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.server_tab = QtWidgets.QWidget()
        self.server_tab.setObjectName("server_tab")
        self.ipAddress = QtWidgets.QLineEdit(self.server_tab)
        self.ipAddress.setGeometry(QtCore.QRect(198, 208, 307, 42))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ipAddress.setFont(font)
        self.ipAddress.setObjectName("ipAddress")
        self.portNumber = QtWidgets.QLineEdit(self.server_tab)
        self.portNumber.setGeometry(QtCore.QRect(198, 331, 307, 42))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.portNumber.setFont(font)
        self.portNumber.setObjectName("portNumber")
        self.runButton = QtWidgets.QPushButton(self.server_tab)
        self.runButton.setGeometry(QtCore.QRect(198, 263, 168, 55))
        self.runButton.setObjectName("runButton")
        self.currentStatus = QtWidgets.QLabel(self.server_tab)
        self.currentStatus.setGeometry(QtCore.QRect(20, 20, 352, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.currentStatus.setFont(font)
        self.currentStatus.setObjectName("currentStatus")
        self.label = QtWidgets.QLabel(self.server_tab)
        self.label.setGeometry(QtCore.QRect(20, 208, 165, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.server_tab)
        self.label_2.setGeometry(QtCore.QRect(20, 331, 71, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.usingDocker = QtWidgets.QCheckBox(self.server_tab)
        self.usingDocker.setGeometry(QtCore.QRect(198, 386, 230, 44))
        self.usingDocker.setObjectName("usingDocker")
        self.label_3 = QtWidgets.QLabel(self.server_tab)
        self.label_3.setGeometry(QtCore.QRect(20, 443, 122, 43))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(self.server_tab)
        self.textEdit.setGeometry(QtCore.QRect(3, 515, 521, 391))
        self.textEdit.setObjectName("textEdit")
        self.tabWidget.addTab(self.server_tab, "")
        self.database_tab = QtWidgets.QWidget()
        self.database_tab.setObjectName("database_tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.database_tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 521, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.loadBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.loadBtn.setObjectName("loadBtn")
        self.verticalLayout.addWidget(self.loadBtn)
        self.user_btn = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.user_btn.setObjectName("user_btn")
        self.verticalLayout.addWidget(self.user_btn)
        self.contact_btn = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.contact_btn.setObjectName("contact_btn")
        self.verticalLayout.addWidget(self.contact_btn)
        self.message_btn = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.message_btn.setObjectName("message_btn")
        self.verticalLayout.addWidget(self.message_btn)
        self.tabWidget.addTab(self.database_tab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setRowCount(13)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        self.horizontalLayout.addWidget(self.tableWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1943, 41))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Message Server"))
        self.ipAddress.setText(_translate("MainWindow", "0.0.0.0"))
        self.portNumber.setText(_translate("MainWindow", "5000"))
        self.runButton.setText(_translate("MainWindow", "Run!"))
        self.currentStatus.setText(_translate("MainWindow", "Current number of user:"))
        self.label.setText(_translate("MainWindow", "Starting IP:"))
        self.label_2.setText(_translate("MainWindow", "Port:"))
        self.usingDocker.setText(_translate("MainWindow", "Using docker"))
        self.label_3.setText(_translate("MainWindow", "Output:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.server_tab), _translate("MainWindow", "Server"))
        self.loadBtn.setText(_translate("MainWindow", "Load"))
        self.user_btn.setText(_translate("MainWindow", "User table"))
        self.contact_btn.setText(_translate("MainWindow", "Contact table"))
        self.message_btn.setText(_translate("MainWindow", "Message table"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.database_tab), _translate("MainWindow", "Database"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

